### PR TITLE
Quick and easy CSS change that is prettier in my opinion

### PR DESCRIPTION
**Pull request by ghost**
Fixed the padding on the volume bar so that when it is slid all the way to the right (100%) there is no longer extra length on the end. Small but needed change visually.

### CODE REVIEW

**Comment by ghost** [comment]
Hi @swimmadude66 

Any idea on why github thinks this simple change cannot be auto merged and needs resolving? Seems like it'd be easy. ...

**Comment by Reanmachine** [comment]
The file `styles.css` has been changed since the parent of your commit. You started your development off an old head. The file was changed on Jan 11th in [this commit](https://github.com/swimmadude66/YTRadio/commit/fa9c734057c47250c4aea86946c33487d3eee2dd#diff-e721f60b32bf2c2509d8a5b1d545c9d5) and github does not resolve conflicts automatically. Even though it's on different lines. You should rebase your change onto the head of `master` and resubmit if you want auto-merging, or @swimmadude66 can merge it manually.

**Comment by ghost** [comment]
Crap. Good eye. I shall do that. Thank you.

**Comment by localyost3000** [comment]
not master, rebase on to the head of DevBranch. Also, This PR needs to be targeting YTRadio:DevBranch

**Comment by ghost** [comment]
Yeah I quit

**Comment by localyost3000** [comment]
Basic instructions you asked me to push
1. Fork the repo (which you've done, so now you are set for all future changes!)
2. Pull changes from swimma/YTRadio:DevBranch in to your repo's master
3. Make your changes, test locally
4. Push to your repo
5. Submit PR from your master to swimma/DevBranch

**Pull request closed without merging**
